# fly.toml app configuration file generated for itemskeeper on 2024-08-06T01:19:33-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'itemskeeper'
primary_region = 'qro'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
