# App
spring.application.name=Items Keeper Backend
server.port=8080

# Configuration for PostgreSQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.sql.init.mode=never
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# HikariCP Configuration
spring.datasource.hikari.allow-pool-suspension=true
